### ISSUE TITLE
Can't pause the sound is playing

### ISSUE THREAD

**Issue by thinhc1** [LouisShark/QQChangeVoice#1]
I try to add method pause sound like this
`
JNIEXPORT void JNICALL Java_cn_louis_shark_qqvoice_VoiceFixer_pause
() {
isPlaying= false;
channel->setPaused(true);
channel->stop();

}`
but this not work.
How to pause this sound when it is playing.

**Comment by LouisShark** [comment]
Maybe you can try this 
```
channel->getPaused(&pause);
channel->setPaused(!pause);
```
and look at 
https://www.fmod.com/resources/documentation-api?page=content/generated/FMOD_System_PlaySound.html#/

**Comment by thinhc1** [comment]
Thank you. It really work!
Do you know how to save the sound with effect to sdcard?
